using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

/*

create table tests (
    id int generated by default as identity primary key,
    name varchar(50) character set none,
    modified timestamp computed by (localtimestamp));

insert into tests (name) values ('O’Grady'); // win-1252
insert into tests (name) values ('Entrée');  // iso-8858-1

 */

namespace ScratchpadFx
{
	class Program
	{
		static void Main(string[] args)
		{
			// disable migrations
			Database.SetInitializer<Context>(null);

			DbConfiguration.SetConfiguration(new ContextConfiguration());

			var connectionString =
				"DataSource=localhost;Port=3050;" +
				"User=SYSDBA;Password=masterkey;" +
				"Database=employee;" +
				"Character Set=WIN1252;";

			var context = new Context(connectionString);

			context.Database.Log = Console.WriteLine;

			context.Database.Connection.Open();

			context.Test.Add(new Test()
			{
				//Name = "O\u2019Grady"
				Name = "Entr\u00E9e",
			});

			// the computed column causes a block to be generated
			// EXECUTE BLOCK (p0 VARCHAR(50) CHARACTER SET UTF8 = @p0)
			// RETURNS ("ID" INT, "MODIFIED" TIMESTAMP)
			// the input parameter should be declared as WIN1252 to match the connection string

			context.SaveChanges();
		}

		[Table("TESTS")]
		public class Test
		{
			[Column("ID")]
			public int Id { get; set; }

			[Column("NAME", TypeName = "varchar"), MaxLength(50)]
			public string Name { get; set; }

			[Column("MODIFIED")]
			[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
			public DateTime Modified { get; set; }
		}

		public class Context : DbContext
		{
			public Context(string connectionString) : base(connectionString) { }

			public DbSet<Test> Test { get; set; }
		}

		public class ContextConfiguration : DbConfiguration
		{
			public ContextConfiguration()
			{
				SetProviderFactory("FirebirdSql.Data.FirebirdClient", FirebirdSql.Data.FirebirdClient.FirebirdClientFactory.Instance);
				SetProviderServices("FirebirdSql.Data.FirebirdClient", EntityFramework.Firebird.FbProviderServices.Instance);
			}
		}
	}
}
